name: Deploy to VPS
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: 191.101.70.64
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ../var/www/html/ERP
          git pull
